apiVersion: v1
kind: Pod
metadata:
  name: stress-test-sandbox
  labels:
    app: stress-test-sandbox
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    args:
    - sleep
    - infinity
    resources:
      limits:
        memory: "256Mi"
        cpu: "0.5"
      requests:
        memory: "128Mi"
        cpu: "0.3"
