apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
      # Toleration to allow the pod to be scheduled on nodes with the "gpu" taint
      tolerations:
      - key: gpu
        operator: Equal
        value: "true"
        effect: NoSchedule

