apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: replica-teste
  name: nginx-teste-replica-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: replica-teste
  template:
    metadata:
      labels:
        app: replica-teste
    spec:
      containers:
      - image: nginx:1.19.3
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.25"
            memory: "128Mi"
