apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 8080 # Porta do Service
      targetPort: 80 # Porta dos Pods